### ISSUE TITLE
airport and military cars

### ISSUE THREAD

**Issue by hemato** [DK-DonnieKongy/LosOce_TA#1]
how to disable military and airport cars , planes etc. ?
http://prntscr.com/oxt9dj

**Comment by DK-DonnieKongy** [comment]
My script lowers traffic and disables police.

Nowhere did I mention it would remove military vehicles.

This is not an issue with my script.
Please find something else on the FiveM Forums to assist you,.

I recommend having a look at the native : 
SetVehicleModelIsSuppressed(
	model --[[ Hash ]], 
	suppressed --[[ boolean ]]
)
